### ISSUE TITLE
fetch does not wait for JS to execute

### ISSUE THREAD

**Issue by burhanuday** [rocktimsaikia/meta-fetcher#10]
some websites will have their meta tags populated by JS. Since we are fetching the HTML contents of the page before JS has been loaded, the meta tags will never be filled

eg. the results of fetching meta tags for https://twitter.com/ManjaroLinux will all be empty strings because the meta tags are loaded by the JS

a way to solve this problem would be to use somthing like Selenium or Puppeteer to wait for the page to load before getting the HTML contents.

This is a major blocker since a lot of websites now use client side rendering and this library does not work in those cases.

**Comment by rocktimsaikia** [comment]
That is a valid concern. This lib was not intended to be dealing with dynamic meta tags initially. I wanted the implementation to be very simple using only fetch API. Adding something like `Puppeteer` will be expensive to this lib. Maybe there are alternative packages that deals with this issue? If not then that will be another package idea to invest some time on that deals with dynamic meta tags specifically.

**Comment by burhanuday** [comment]
Agreed
