### ISSUE TITLE
Add support for default export in the next major release

### ISSUE THREAD

**Issue by rocktimsaikia** [rocktimsaikia/meta-fetcher#2]

**Comment by quriosapien** [comment]
Is there any roadmap for the next release ??

**Comment by rocktimsaikia** [comment]
@ikmrgrv  This type of simple module is basically complete once published. There is no addition of a new feature out of the blue unless there is a bug on how it works. Not using default export was a mistake on my side. But I can't just change it now since this will be a breaking change. So I am thinking unless there is any major bug or feature request , I am going to keep it this way.
