### ISSUE TITLE
change the meta tag name

### ISSUE THREAD

**Issue by shoaibsharif** [rocktimsaikia/meta-fetcher#9]
Hi,
First of all, thank you for this npm package. It actually helps me a lot. While I was working on a project, I have noticed it has a tiny issue when I tried to get `og:image` from head. Upon researching, I have found that [you are trying to find](https://github.com/rocktimsaikia/meta-fetcher/blob/main/src/index.ts#L26) `'meta[name="og:image"]'` where I think you should find `'meta[property="og:image"]'`.

**Comment by rocktimsaikia** [comment]
That's a valid issue but some sites do attach the Social image with the `name` attribute. So we can check for the `property` attribute first if not present the fallback to the `name` attribute.

PRs welcome.
